### ISSUE TITLE
newly created tutorial throws `InvalidContentEntryFrontmatterError` 

### ISSUE THREAD

**Issue by web-dave** [stackblitz/tutorialkit#118]
### Describe the bug

New created Project does not work.
It throws 
```
[ERROR] [InvalidContentEntryFrontmatterError] tutorial → meta.md frontmatter does not match collection schema.
Unrecognized key(s) in object: 'title'
  Hint:
    See https://docs.astro.build/en/guides/content-collections/ for more information on content schemas.
  Error reference:
    https://docs.astro.build/en/reference/errors/invalid-content-entry-frontmatter-error/
  Stack trace:
    at /Users/davidmullerchen/workspace/OSS/first-try-js/src/content/tutorial/meta.md
    [...] See full stack trace in the browser, or rerun with --verbose.
    ```

### Steps to reproduce

npm creat tutorial
...
cd tutarial
npm run dev

### Expected behavior

it works at keast on init

### Platform

- TutorialKit version: [e.g. 1.0.1]
- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by web-dave** [comment]
my-tutorial/src/content/tutorial/meta.md
```md
---
type: tutorial
title: Basics
mainCommand: ["npm run dev", "Starting http server"]
prepareCommands:
  - ["npm install", "Installing dependencies"]
---
```
There is an unexpected `title`

**Comment by AICDEV** [comment]
your fix in https://github.com/stackblitz/tutorialkit/commit/c2f7688b27074c6261f025525437bccea9431fd3 is not in your latest package version: https://www.npmjs.com/package/tutorialkit?activeTab=versions  ;-) Debugged with ❤️ by webdaves mob

**Comment by Nemikolh** [comment]
Hey @AICDEV and @web-dave! :wave: Thanks for the report!

We'll publish a new version soon.

**Comment by AriPerkkio** [comment]
There's now new release `0.0.1-alpha.25` that fixes this issue. You can create a new project with `npm create tutorial@latest` or update the `@tutorialkit/*` packages to the latest version in your `package.json`.
