### ISSUE TITLE
Add Github icon link on top of demo.tutorialkit.dev `TopBar`

### ISSUE THREAD

**Issue by AriPerkkio** [stackblitz/tutorialkit#129]
### Is your feature request related to a problem?

The demo page https://demo.tutorialkit.dev doesn't have link to TutorialKit's sources. 

### Describe the solution you'd like.

Similar solution as done in https://github.com/ariperkkio/tutorial-vite-plugin/pull/7.

Apply it here: https://github.com/stackblitz/tutorialkit/tree/main/docs/tutorialkit.dev

**Comment by Charan167** [comment]
Hello! I wanna work on this issue. Please let me know what exactly are TutorialKit's sources.

**Comment by AriPerkkio** [comment]
Source code for `demo.tutorialkit.dev` is at https://github.com/stackblitz/tutorialkit/tree/main/docs/demo.
