### ISSUE TITLE
Add `terminalOpen` to frontmatter metadata

### ISSUE THREAD

**Issue by AriPerkkio** [stackblitz/tutorialkit#132]
### Is your feature request related to a problem?

It's not possible to have lessons where terminal is open by default. In tutorial lessons like https://tutorial-vite-plugin.pages.dev/1-vite-plugin/2-env-plugin/4-env-variables-in-load-hook/ I need to guide users to manually click the terminal open.

### Describe the solution you'd like.

Add an option to frontmatter metadata for setting terminal open by default. 

```md
---
type: lesson
title: Some lesson
terminalOpen: true. # <-- New option, sets terminal open
---
```

**Comment by Nemikolh** [comment]
Would it maybe make more sense to have it as a property of the `terminal` configuration?

Like `open`:

```md
---
type: lesson
title: Some lesson
terminal:
  open: true
---
```

Otherwise you could end up with this:

```md
---
type: lesson
title: Some lesson
terminalOpen: true
terminal: false
---
```

**Comment by AriPerkkio** [comment]
Oh right there is already `terminal` option. Let's add this option there!
