### ISSUE TITLE
Do not exclude config file in VS code

### ISSUE THREAD

**Issue by eric-burel** [stackblitz/tutorialkit#164]
### Is your feature request related to a problem?

Hi, it took me some time to figure that the project was using file exclusion in .vscode to hide the config (astro.config etc.)
The documentation mentions an astro.config file we may tweak to customize the project and I couldn't find it, and honestly started to believe TutorialKit was working with some magic I couldn't comprehend ':)

Files I see, and the VS code setting
![image](https://github.com/user-attachments/assets/89576a52-27fd-4550-8e8d-94eaeaade4c3)

### Describe the solution you'd like.

Not hide the config, I'd rather see the astro config in the files in vs code to figure how TutorialKit works

### Describe alternatives you've considered.

Move the config to a hidden folder so it doesn't clutter the root of the folder but can still be available, in Vulcan Next we used to have a `.vn` for that

**Comment by AriPerkkio** [comment]
We are planning to remove whole `.vscode/settings.json`. It's been listed in v1 roadmap: https://github.com/stackblitz/tutorialkit/issues/144

PR welcome! 🙌

**Comment by eric-burel** [comment]
Thanks I'll keep track of the v1 roadmap and close in the meanwhile, so far it's already working great!
