### ISSUE TITLE
Initial setup (CSS) broken on Windows 

### ISSUE THREAD

**Issue by LukasSonnabend** [stackblitz/tutorialkit#182]
### Describe the bug

Hello I just setup a new Tutorialkit Project, unfortunately using Node 22.4.1/22.2.0 and running npx tutorialkit create the result is broken on Windows 11 (it seems some of the CSS is not loading). On my Mac with the same Node Version the CSS is working.

### Link to a StackBlitz project which shows the error

[Stackblitz Repro (not broken because not on windows?)](https://stackblitz.com/~/github.com/LukasSonnabend/tutorialkit-repro)

### Steps to reproduce

1. npx tutorialkit create
2. Yes to all
3. Visit link in Terminal

### Expected behavior

The initial State after running npx tutorialkit create should be working across OS.

### Screenshots

Found Behaviour
![grafik](https://github.com/user-attachments/assets/363f6106-1dad-4898-9a5a-a87a2fb638e8)

Expectation is the way the Demo looks: 
![grafik](https://github.com/user-attachments/assets/1a279083-a863-4a7a-8981-f212f63cc7dd)

### Platform

- TutorialKit version: 0.1.1
- OS: Windows 11
- Browser: Chrome, Edge, Firefox
- Version: 126.0.6478.128, 126.0.2592.113, 129.0b8 (64-bit)

**Comment by AriPerkkio** [comment]
Could you try if following change in `uno.config.ts` fixes the issue?

```diff
-import { basename, dirname, join } from 'node:path';
+import { basename, dirname, join, sep } from 'node:path';

...

content: {
  inline: globSync([
-    `${convertPathToPattern(join(require.resolve('@tutorialkit/astro'), '..'))}/default/**/*.astro`,
-    `${convertPathToPattern(join(require.resolve('@tutorialkit/components-react'), '..'))}/**/*.js`,
+    `${convertPathToPattern(join(require.resolve('@tutorialkit/components-react'), '..')).replaceAll(sep, "/")}/**/*.js`,
+    `${convertPathToPattern(join(require.resolve('@tutorialkit/astro'), '..')).replaceAll(sep, "/")}/default/**/*.astro`,
  ]).map((filePath) => {
    return () => fs.readFile(filePath, { encoding: 'utf8' });
  }),
},
```

We are planning to provide better way to handle `uno.config.ts`, so that this much logic would not end up in end-users configurations.
