### ISSUE TITLE
Preview window has height 0

### ISSUE THREAD

**Issue by noam-honig** [stackblitz/tutorialkit#183]
### Describe the bug

Tried to get started both with npm create tutorial and with `npx tutorialkit create` and in both cases I wasn't able to see the preview:
![image](https://github.com/user-attachments/assets/09147b80-9c2b-40c8-ba37-ec82e2124e45)

### Steps to reproduce

1. `npm create tutorial`
2. open browser
3. see missing preview.

### Expected behavior

I expected to see the preview - I also expected the default styling to be a bit better

### Screenshots

![image](https://github.com/user-attachments/assets/447642e0-9d36-475f-aea4-fd7a1979ea2c)

### Platform

- TutorialKit version: 0.1.0
- OS: Windows
- Browser: Chrome
- Version: latest

**Comment by AriPerkkio** [comment]
This looks same as https://github.com/stackblitz/tutorialkit/issues/182. 

Could you try applying the fix from https://github.com/stackblitz/tutorialkit/pull/184/files on your `uno.config.ts`?

**Comment by noam-honig** [comment]
Yeah - look like that did it
