### ISSUE TITLE
Adding urls to the `previews` definition

### ISSUE THREAD

**Issue by noam-honig** [stackblitz/tutorialkit#192]
### Is your feature request related to a problem?

I want to show several preview tabs - with different relative urls for example:
{port:5173, title:"frontend"}
{port:5173, title:"api",url:"/api/tasks"}
{port:5173, title:"admin",url:"/api/admin"}

### Describe the solution you'd like.

I want to show several preview tabs - with different relative urls for example:
{port:5173, title:"frontend"}
{port:5173, title:"api",url:"/api/tasks"}
{port:5173, title:"admin",url:"/api/admin"}

### Describe alternatives you've considered.

reviewed the https://tutorialkit.dev/reference/configuration/ url and couldn't find anything

**Comment by AriPerkkio** [comment]
Currently this is not possible but we are planning to add support for it. I've done some design for the possible API earlier:

> ```yaml
> previews: 
>    - 1234/pathname
>    - [1234/pathname, 'Title']
>    - { port: 1234, path: '/pathname', title: 'Title' }
> ```

**Comment by AriPerkkio** [comment]
Released in `0.1.5`.
