### ISSUE TITLE
Tutorial Env Vars

### ISSUE THREAD

**Issue by sosensible** [stackblitz/tutorialkit#195]
### Is your feature request related to a problem?

We would like to be able to teach people technologies like Supabase with this tool.

### Describe the solution you'd like.

We need to store private variables and have them not exposed to repo pushes, etc. Making a file extension that could store the variables locally along the lines of the .env file would work if that were added to the .gitignore.

### Describe alternatives you've considered.

The alternative is a containerized package with VSCode reaching into the container.

**Comment by Nemikolh** [comment]
Hey @sosensible! A tutorial for Supabase sounds really interesting! 🤩🤩

TutorialKit uses astro under the hood and [everything mentioned in their docs regarding environment variables](https://docs.astro.build/en/guides/environment-variables/) should work.

Could you provide more details on what you tried or want to achieve?

**Comment by sosensible** [comment]
This should work, not sure why my search missed that. Kudos for the gracious response.

**Comment by Nemikolh** [comment]
No problem! Let us know how writing your tutorial goes! 😃
