### ISSUE TITLE
Starting dev server for an Angular app fails

### ISSUE THREAD

**Issue by vscaiceanu-1a** [stackblitz/tutorialkit#196]
### Describe the bug

I'm trying to write a tutorial using an Angular app but the dev server fails to start.

### Steps to reproduce

clone https://github.com/vscaiceanu-1a/tutorialkit-angular
`npm install`
`npm start`

go to http://localhost:4321/

Starting http server fails with:
```shell
> ng serve

jsh: permission denied: ng
```

### Expected behavior

The app should be served

### Platform

- TutorialKit version: 0.1.1
- OS: macOS
- Browser: Chrome
- Version: 126.0.6478.185

**Comment by AriPerkkio** [comment]
This sounds similar as

- https://github.com/stackblitz/tutorialkit/discussions/187
- https://github.com/stackblitz/tutorialkit/issues/190

Could you try if removing `templated/*/node_modules` works?

**Comment by vscaiceanu-1a** [comment]
It does work indeed.
Thank you!

**Comment by AriPerkkio** [comment]
Perfect! We'll prioritize https://github.com/stackblitz/tutorialkit/issues/189 next so that `node_modules` would be ignored by default automatically.
