### ISSUE TITLE
Slug customization failing in content.md file

### ISSUE THREAD

**Issue by geromegrignon** [stackblitz/tutorialkit#197]
### Describe the bug

As explained during the last stream by an attendee, `slug` customization do not work for **lesson**.
it's fine for chapter/part.

Trying to add the property with a value results in this page error:

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/bd779a8a-207e-46ca-b02c-ae213112f295">

### Steps to reproduce

1. Create a TutorialKit project
2. open the content.md file from the demo tutorial
3. add a **slug** property in the frontmatter part
4. run the project

### Expected behavior

The app should run AND get an updated URL

### Screenshots

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/3adc1f8a-7948-47b3-ae62-8f5bf4d8b4ca">

### Platform

- TutorialKit version: [e.g. 1.0.1]
- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

I tried to run the docs/demo as it uses it but i was stuck on this error by running the `pnpm run demo`script:

```
Failed to resolve entry for package "@tutorialkit/astro". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by AriPerkkio** [comment]
> ### Steps to reproduce
> 1. Create a TutorialKit project
> 2. open the content.md file from the demo tutorial
> 3. add a **slug** property in the frontmatter part
> 4. run the project

I've tried to follow these steps with follow:
1. `pnpm create tutorial`
2. `cd <project>; code src/content/tutorial/1-basics/1-introduction/1-welcome/content.md`
3. ```diff
   ---
   type: lesson
   title: Welcome to TutorialKit
   focus: /counter.js
   + slug: some-custom-lesson-slug
   ---
   ```
4. `pnpm run dev`
5. URL `http://localhost:4321/1-basics/1-introduction/some-custom-lesson-slug` opens up ✅ 
6. Check that we are using latest versions:
   > `cat package.json | grep tutorialkit`
   >   "@tutorialkit/components-react": "0.1.1",
   >   "@tutorialkit/astro": "0.1.1",
   >   "@tutorialkit/types": "0.1.1",

Could you try the steps above, and modify them in a way that causes the error?

**Comment by geromegrignon** [comment]
Hi @AriPerkkio, thanks for the feedback.

That's pretty strange as it both works on a new project and the existing one today.

Closing it as i can't reproduce it. Thanks for your time!
