### ISSUE TITLE
Update _files content with scrips command

### ISSUE THREAD

**Issue by geromegrignon** [stackblitz/tutorialkit#208]
### Is your feature request related to a problem?

I'm creating a NgRx (Angular state management library) and the first step is to add the library with the `ng add @ngrx/store@latest`. It adds the dependency in package.json and updates some files.

I added all these files in the _files folder as the student task is to run the script and sees how it affect the project.
However even if the command succeeds, the files are not updated.

### Describe the solution you'd like.

_files content should be updated from terminal action.

### Describe alternatives you've considered.

No alternative

**Comment by GaetanRdn** [comment]
The solution for this problem could be the same for https://github.com/stackblitz/tutorialkit/discussions/204 in a first time.
