### ISSUE TITLE
Subfolders on windows do not work

### ISSUE THREAD

**Issue by noam-honig** [stackblitz/tutorialkit#209]
### Describe the bug

I'm using windows, I've added a file to a sub folder:
`src\content\tutorial\1-basics\1-introduction\1-welcome\_files\src\file-in-src.js`
Probably since I'm using windows it confuses it, instead of showing a folder and a file, it shows the full path,
and when I click it - I see an empty file.

![image](https://github.com/user-attachments/assets/227063ba-2ad8-4f54-91bc-878d72354a7f)

Checkout this repo:
https://github.com/noam-honig/play-with-tutorial-kit/

### Steps to reproduce

1. Use windows
2. Add a file called `src\content\tutorial\1-basics\1-introduction\1-welcome\_files\src\file-in-src.js`
3. Restart the dev server.
4. See that the file looks wrong and doesn't open

### Expected behavior

Expected to show a folder tree with files in it, and when the files are clicked - see that they open

### Screenshots

![image](https://github.com/user-attachments/assets/317b1677-58d1-47a5-96f2-3d7e0f22f2e7)

### Platform

- TutorialKit version: 0.1.2
- OS: Windows
- Browser: chrome
- Version: [e.g. 91.1]

**Comment by AriPerkkio** [comment]
I can reproduce this on virtualized Windows 11 too. 

We should really add unit test for this and make sure it's run on Windows CI. I would start debugging from these files first:

https://github.com/stackblitz/tutorialkit/blob/cc50ad4d90d6ffb42f3a658de08f9617826b6c07/packages/runtime/src/lesson-files.ts#L12

https://github.com/stackblitz/tutorialkit/blob/cc50ad4d90d6ffb42f3a658de08f9617826b6c07/packages/astro/src/default/utils/content.ts#L81-L82

**Comment by noam-honig** [comment]
FYI - in the meantime, I switch to `wsl` (linux on windows) and it seems ok there

**Comment by AriPerkkio** [comment]
This is fixed in latest `0.1.4` release. Update the `@tutorialkit/*` packages in your `package.json` to latest version and Windows should work fine.

**Comment by noam-honig** [comment]
Hi @AriPerkkio Tested - it works great
