### ISSUE TITLE
Ability to include code from the `_files` in the markdown of the lesson

### ISSUE THREAD

**Issue by noam-honig** [stackblitz/tutorialkit#264]
### Is your feature request related to a problem?

In many cases the code blocks in my markdown is the same code from the `_files` or `_solution` - and keeping it consistent is not ideal

### Describe the solution you'd like.

I wish I could reference to a a file in the lesson from the code.

Something like
```
```ts src="frontend/Todo.tsx:lines(10-15)" title="same as src" add={1-5}
```
```

### Describe alternatives you've considered.

Maintaining both versions

### Additional context

_No response_

**Comment by AriPerkkio** [comment]
Interesting idea! At first I was thinking this should be solved in userland by creating custom Astro components that simply read the file contents with `node:fs` and show them in markdown. But I think quite many tutorials would benefit of this feature, it would be nice to have it built in TutorialKit.

**Comment by Nemikolh** [comment]
We already support this feature actually! It's not documented but you can do it with:


    ```file:/path/to/file.js
    ```

See https://github.com/stackblitz/tutorialkit/pull/18

**Comment by AriPerkkio** [comment]
Let's add documentation for this in https://github.com/stackblitz/tutorialkit/issues/250.

**Comment by noam-honig** [comment]
@AriPerkkio the existing solution is only partial - I need the ability to select which lines will be included from the source file.

Sometimes the source file can be 40 lines, with changes to two - I want to focus on 5 lines and highlight the change in these two

**Comment by AriPerkkio** [comment]
Does the `collapse` option work there?

```yaml
\```file:/vite.config.ts showLineNumbers {7-11} collapse={1-4, 13-19}

\```
```

<img src="https://github.com/user-attachments/assets/f4dcb098-b720-4fe5-a7b2-12347c84018a" width="400" />

**Comment by noam-honig** [comment]
Sure - that's good enough.

Is there a specific md page you want me to document all of this in?

**Comment by noam-honig** [comment]
Hi @AriPerkkio I would like to document these options - can you let me know which package are you using for the code snippets - so I'll investigate their docs? and also which one is being used for markdown?

**Comment by AriPerkkio** [comment]
> Is there a specific md page you want me to document all of this in?

I think `guides/creating-content` would be a good spot for this. 

> which package are you using for the code snippets - so I'll investigate their docs? and also which one is being used for markdown?

TutorialKit supports [`expressive-code`](https://expressive-code.com/key-features/syntax-highlighting/) and [Astro](https://docs.astro.build/en/guides/content/).
