### ISSUE TITLE
Component docs contain references to excluded files

### ISSUE THREAD

**Issue by AriPerkkio** [stackblitz/tutorialkit#287]
### Describe the bug

In terminal example at https://tutorialkit.dev/reference/react-components/ there is import for `useTheme.ts` file that is not visible in the page, or in the linked Stackblitz project. There's no way for users to know what it contains.

```ts
import { useTheme } from './hooks/useTheme';
```

### Steps to reproduce

https://tutorialkit.dev/reference/react-components/

### Expected behavior

Documentation should contain all code that is required to reproduce the example. Ideally users should not even open the linked Stackblitz project to see what the referenced files contain. 

### Platform

- TutorialKit version: 0.2.0

**Comment by Nemikolh** [comment]
We could introduce that file as a code snippet somewhere at the start of the page. In particular, it's not been shown because the actual implementation used in the docs is specific to our docs and not relevant for end users.
