### ISSUE TITLE
Parts of only one lesson

### ISSUE THREAD

**Issue by eric-burel** [stackblitz/tutorialkit#304]
### Is your feature request related to a problem?

I'd like to write intro/outro parts that may not need a 3-level subdivision between part, chapter and lesson.

Currently, I need multiple levels so my introduction page maybe `/getting-started/intro/about", instead of just `/getting-started`. The UX is not as smooth as it could when it comes to writing proper course introductions or conclusions.

### Describe the solution you'd like.

Allow having 2-levels or 1-level hierarchy.

```
intro
|_ _files
|_ content.md
|_ meta.md
short-part
|_ chapter-1
|__ _files
|__ content.md
```

### Describe alternatives you've considered.

This seems a little change but I understand how this can affect UX.
- We could allow having content in parts and chapters ? Maybe have special "intro.md"/"ending.md" files ?
- Or keep content only in type "lesson", but allow a lesson to live outside of a chapter or part ? In this approach, as a default, we write lessons in a tutorial. Optionally, we can move lessons to a chapter. And optionnaly, we can move chapters into parts.
- We could instead craft independant Astro pages, and focus on linking them to specific courses via meta data? For instance adding an "outro: /some-page" field to the chapter definition or something alike. But seems convoluted, mixing the mental model of Astro and the mental model of Tutorialkit.

### Additional context

The file `packages/astro/src/default/utils/routes.ts` seems to be responsible to route creation and could be tweaked quite easily. However such a change may have consequences on the mental model around parts/chapters/lessons in other places.

**Comment by Nemikolh** [comment]
Thanks for opening this issue! 

I agree with the general idea proposed here, although I would instead allow the tutorial meta to have lessons or chapters which would achieve the same thing but keep the existing logic for parts and chapters.

If we don't allow mixed hierarchies where a tutorial has both parts and chapters / lessons, then it should be pretty easy to add.
