### ISSUE TITLE
Codemirror - show syntax errors

### ISSUE THREAD

**Issue by iliakan** [stackblitz/tutorialkit#329]
How can I enable showing syntax errors in CodeMirror? Like a normal editor.

CodeMirror has linter for this:
- https://codemirror.net/examples/lint/

I'm not familiar with it, but here's an example of using it:
- https://discuss.codemirror.net/t/codemirror-6-customize-linter/8211

Do I need to patch tutorialkit, or there's a better solution?

**Comment by AriPerkkio** [comment]
In https://github.com/stackblitz/tutorialkit/issues/213 we'll be adding support for showing syntax errors for Javascript.
