### ISSUE TITLE
File extension based icons in `FileTree`

### ISSUE THREAD

**Issue by AriPerkkio** [stackblitz/tutorialkit#331]
### Is your feature request related to a problem?

Icons of the files in file tree use same icon for every single file type.

<img src="https://github.com/user-attachments/assets/310964fd-6681-4942-baa6-432b81ed1db7" width="300" />

### Describe the solution you'd like.

Let's use file specific icons for files. Unknown extensions should fallback to the generic icon.

https://icon-sets.iconify.design/ph/?query=file-

**Comment by AriPerkkio** [comment]
@Charan167 could you create a pull request with the changes? Let's take a look at the code there and see if any changes are needed. 🙌

**Comment by Charan167** [comment]
Hey! I've created a PR but it has failed some checks probably due to the multiline comment present in the file. I’d love to hear your thoughts on both the icons and the code itself so I can tweak things accordingly and push a better version.
