### ISSUE TITLE
Warning `Property defaultPreviewTitleText is not allowed` in VSCode extension

### ISSUE THREAD

**Issue by ycs77** [stackblitz/tutorialkit#337]
### Describe the bug

Before adding a new i18n property `defaultPreviewTitleText` in #255, but now the warning `Property defaultPreviewTitleText is not allowed` remains in the VSCode.

### Steps to reproduce

1. create a new Tutorialkit project
2. open VSCode and install Tutorialkit VSCode extension
3. open `src/content/tutorial/meta.md`
4. add below i18n content:

```yaml
i18n:
  defaultPreviewTitleText: '預覽'
```

5. see the warning `Property defaultPreviewTitleText is not allowed` when the mouse hovering `defaultPreviewTitleText`

### Expected behavior

No show the `Property defaultPreviewTitleText is not allowed` warning.

### Screenshots

![螢幕擷取畫面 (214)](https://github.com/user-attachments/assets/d6474bd7-58c1-4bf7-8c68-c0128e99e2e1)

### Platform

- TutorialKit version: 0.2.3
- OS: Windows
- Browser: not applicable
- Version: [e.g. 91.1]

### Additional context

The i18n contentSchema is in the `@tutorialkit/types` package:

https://github.com/stackblitz/tutorialkit/blob/5c1de69c0e4e233a25a2f9b70fbb1f6c93f12356/packages/types/src/schemas/i18n.ts#L109-L114

And this is code of load the `contentSchema` in the vscode extension:

https://github.com/stackblitz/tutorialkit/blob/5c1de69c0e4e233a25a2f9b70fbb1f6c93f12356/extensions/vscode/scripts/load-schema-worker.mjs#L2-L5

https://github.com/stackblitz/tutorialkit/blob/5c1de69c0e4e233a25a2f9b70fbb1f6c93f12356/extensions/vscode/scripts/build.mjs#L61-L71

So if rebuilding the vscode extension can this warning be resolved?

**Comment by AriPerkkio** [comment]
The extension bundles `@tutorialkit/types`. This means that we need to re-publish it every time we make changes to `@tutorialkit/types`.

So this should start working once we publish new version of extension.

**Comment by AriPerkkio** [comment]
There is now new version of the extension published that fixes this issue.
