### ISSUE TITLE
Accessing File Tree with Source Codes as a JSON

### ISSUE THREAD

**Issue by rainmakersumit** [stackblitz/tutorialkit#341]
### Is your feature request related to a problem?

I need the full code base including the user changes so that we can evaluate the code and get back to him with a report. 

### Describe the solution you'd like.

If I get the entire file tree and user code changes as JSON then It would be easier to evaluate. 

### Describe alternatives you've considered.

Not Applicable.

**Comment by AriPerkkio** [comment]
There are couple of options:

1. Use the "Open In StackBlitz" button on top of the TutorialKit, and use those to "store" user's results. So basically when you click this ⚡ button, you get link to stackblitz.com with the current state of the editor. It includes all lesson and template files, including the modifications that user did.

<img src="https://github.com/user-attachments/assets/de543792-077f-4ea1-9afe-273ddb0f0271" width="400" />

2. Create your own custom component that calls TutorialKit's public APIs to get current state of the file system + editor. This is the same data as in option `#1`, but here you can process the JSON anyway you want. Here is example where we simply print the JSON on the page:

https://stackblitz.com/~/edit/tutorialkit-store-snapshot?file=src/components/SnapshotButton.tsx&file=src/content/tutorial/1-basics/1-introduction/1-welcome/content.mdx

```ts
import tutorialStore from 'tutorialkit:store';

// Save current state of the file system
const snapshot = tutorialStore.takeSnapshot();
```

![image](https://github.com/user-attachments/assets/3fb76dbc-a8e2-4f7e-a413-51797fc776dd)


Does this help?

**Comment by learnwithsumit** [comment]
Thanks. Worked

**Comment by rainmakersumit** [comment]
Solved, I have another question
![image](https://github.com/user-attachments/assets/0637d54a-c211-4d6f-8b91-aa70ecf42bce)

Can I hide this button ? Without CSS ? 
Basically I was looking for full control over the system
I need to add Custom Button Over there, is it possible ?

**Comment by AriPerkkio** [comment]
> Can I hide this button ? Without CSS ?

At the moment we don't support hiding the Solve/Reset -button. Feel free to open feature request for this.

> Solved

Great, let's close this issue then.
