### ISSUE TITLE
No preview & styling issues.

### ISSUE THREAD

**Issue by MirjamElad** [stackblitz/tutorialkit#382]
### Describe the bug

Hello everyone & thank you for this promissing "framework",

I just started testing tutorialkit less than three hours ago (Meaning the very last release at the time of me writing this message).
Upon running > `pnpm create tutorial` and without making any changes. I get a result on (see first image) `http://localhost:4321/1-basics/1-introduction/1-welcome` that doesn't have a proper **preview**, also styling seems wrong and doesn't match what Tomek Sułkowski's presentation shows (see seconde image)

The main screen on my machine
![image](https://github.com/user-attachments/assets/be08b76c-2448-45ed-ae63-9b5160ece9b1)

The main screen as presented by Tomek Sułkowski here: [Tomek Sułkowski | TutorialKit: In-Browser Teaching for All! | ViteConf 2024](https://www.youtube.com/watch?v=ixJh-X2QpTA)
![image](https://github.com/user-attachments/assets/32bc965f-5e35-4e80-91b9-6068483e5ba3)

Note that I am on a Windows 11 machine and I use VsCode (not that it should matter)

### Steps to reproduce

As I said earlier. Nothing special, I just run the project as specified in [the guide](https://tutorialkit.dev/guides/installation/)

### Expected behavior

I'd expect it to work as advertized. Again, I did not add a single character, just run it and the result were not as described above.

### Screenshots

![image](https://github.com/user-attachments/assets/3f9b75c5-ae22-47f5-9e09-c7a8105f3a11)

### Platform

- TutorialKit version: [e.g. 1.0.1]
- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by AriPerkkio** [comment]
What versions of `@tutorialkit` packages do you have in `package.json`?

**Comment by MirjamElad** [comment]
The suggested windows [fix](https://github.com/stackblitz/tutorialkit/pull/184/files) is no longer straight forward to apply.
**uno.config.ts** is now basicaly empty

**Comment by AriPerkkio** [comment]
Yep, that old work-around won't work for this one unfortunately. We will prioritise this issue in the beginning on next week and get this fixed as soon as possible.

**Comment by AriPerkkio** [comment]
This is now fixed and released in [`v1.1.1`](https://github.com/stackblitz/tutorialkit/releases/tag/1.1.1).
