### ISSUE TITLE
`npm run build` command does not work

### ISSUE THREAD

**Issue by morinokami** [stackblitz/tutorialkit#53]
### Describe the bug

When I try to build a project created with the `npx tutorialkit@latest create` command, I get the following error:

```sh
$ npm run build

> round-boat@0.0.1 build
> astro check && astro build

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
10:52:12 [types] Added src/env.d.ts type declarations.
✘ [ERROR] The build was canceled

10:52:12 [types] Added src/env.d.ts type declarations.
10:52:12 Types generated 3.32s
10:52:12 [check] Getting diagnostics for Astro files in /Users/sfujino/dev/temp/round-boat...
uno.config.ts:26:35 - error ts(2339): Property 'resolve' does not exist on type 'Require'.

26     inline: globSync(join(require.resolve('@tutorialkit/components-react'), '../**/*.js')).map((filePath) => {
                                     ~~~~~~~

Result (8 files):
- 1 error
- 0 warnings
- 0 hints
```

By the way, I also confirmed that adding

```ts
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
```

to the hidden `uno.config.ts` file fixes the issue.

### Steps to reproduce

1. Run `npx tutorialkit@latest create`
2. `cd` into the project directory
3. Run `npm run build`

### Expected behavior

`npm run build` should generate a `dist` directory

### Platform

- TutorialKit version: 0.0.1-alpha.22
- OS: macOS
- Node.js: v20.14.0
- npm: 10.7.0

**Comment by morinokami** [comment]
As a follow-up, I tried porting the [Vue tutorial](https://vuejs.org/tutorial/) using TutorialKit, and it builds without any problems:

https://github.com/morinokami/vue-tutorialkit (deployed to https://vue-tutorialkit.vercel.app/)

I'm not sure what the difference is, but I wanted to share it anyway.

**Comment by morinokami** [comment]
Hmmm, I have tried again in a clean environment, such as a container, and this problem does not seem to occur. It is 100% reproducible in my environment, but I will close this issue as it is probably environment dependent.

**Comment by d3lm** [comment]
I just looked at your link, pretty cool to see the first tutorial using TutorialKit in the wild! Thanks for trying it out. I am seeing that your page isn't served with the correct COEP/COOP headers which is why your site is not running under `crossOriginIsolation`. For that reason WebContainer won't boot because it relies on `SharedArrayBuffer` and more which requires `crossOriginIsolation` to be enabled. You can learn more about this [here](https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/). The short is your top level site has to serve the following headers:

```
Cross-Origin-Embedder-Policy: 'credentialless' | 'require-corp'
Cross-Origin-Opener-Policy: 'same-origin'
```

**Comment by morinokami** [comment]
@d3lm Thanks for your advice! I added the headers and now it [works on Vercel](https://vue-tutorialkit.vercel.app/) as well!!
