### ISSUE TITLE
Can it be just JS? (no HTML Preview)

### ISSUE THREAD

**Issue by iliakan** [stackblitz/tutorialkit#58]
Let's say the task is pure JS.
Can I disable HTML preview then?

In other words, is it possible to see only output, without HTML preview?

### Describe the solution you'd like.

- Disable HTML-preview for "pure JS" tasks, instead re-run output.

**Comment by Nemikolh** [comment]
Hey @iliakan ! Thanks for opening this issue! Yes you can!

In the metadata of your Tutorial (e.g. in `tutorial/meta.md`), you can have it set to:

```md
---
type: tutorial
previews: false
---
```

This will hide the preview entirely.

**Comment by SamVerschueren** [comment]
Let's close this issue for now. Feel free to create a new one or ask additional questions if you run into anything else.

**Comment by mgd722** [comment]
In case anyone else needs it, here's a link to the [docs for the frontmatter](https://tutorialkit.dev/reference/configuration/#options-reference).
