### ISSUE TITLE
Base deploy path

### ISSUE THREAD

**Issue by steamcleaner** [stackblitz/tutorialkit#89]
### Is your feature request related to a problem?

Currently unable to serve a tutorial with anything other than the default base path of `/`

### Describe the solution you'd like.

Leverage the `import.meta.env.BASE_URL` property that can be configured in the `astro.config` to correctly prefix paths within generated tutorials.

### Describe alternatives you've considered.

N/A

### Additional context

I was able to track down most of the places that needed to be updated. There might be some more that I didn't encounter while I was working through the issues.

- **Logo.astro** : logo file path
- **Layout.astro** : favicon
- **index.astro** : favicon and redirect url
- **content.ts** : lesson next/prev href
- **nav.ts** : href
- **lesson-files.ts** : fetch

**Comment by Nemikolh** [comment]
@steamcleaner Thanks for the report and providing hint at the places that needs to be updated! :smiley: 

It's definitely something we want to fix. Let us know if you'd like to contribute a fix!
